# Generated by Django 2.2.3 on 2019-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_testparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='testParam',
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(),
        ),
    ]
