# Generated by Django 5.2.3 on 2025-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('summary', models.TextField()),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
